name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: bash tectonic.sh
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
          name: test
          path: target/release/tectonic
